---
permalink: sg6000/index.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, maintain, maintaining, hardware, procedures, tasks 
summary: 'Vous devrez peut-être effectuer des procédures de maintenance sur l"appareil SG6000. Les procédures décrites dans cette section supposent que l"appliance a déjà été déployée en tant que nœud de stockage dans un système StorageGRID.' 
---
= Entretenir l'appareil SG6000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devrez peut-être effectuer des procédures de maintenance sur l'appareil SG6000.

Les procédures spécifiques à la maintenance de votre appliance SG6000 sont décrites dans cette section et supposent que l'appliance a déjà été déployée en tant que nœud de stockage dans un système StorageGRID.

Voir link:../commonhardware/index.html["Procédures courantes"] pour les procédures de maintenance utilisées par tous les appareils.

Voir link:../installconfig/configuring-hardware.html["Configurer le matériel"] pour les procédures de maintenance qui sont également effectuées lors de l'installation et de la configuration initiales de l'appliance.

Pour éviter toute interruption de service, vérifiez que tous les autres nœuds de stockage sont connectés au grid avant d'arrêter l'appliance ou de l'arrêter durant une fenêtre de maintenance planifiée en cas d'interruption de service. Voir les informations sur https://docs.netapp.com/us-en/storagegrid-118/monitor/monitoring-system-health.html#monitor-node-connection-states["contrôle de l'état de connexion du nœud"^].


CAUTION: Si vous avez déjà utilisé une règle ILM pour créer une seule copie d'un objet, vous devez arrêter l'appliance durant une fenêtre de maintenance planifiée. Sinon, vous risquez de perdre temporairement l'accès à ces objets pendant toute procédure de maintenance qui met un nœud de stockage hors service. Voir les informations sur https://docs.netapp.com/us-en/storagegrid-118/ilm/index.html["gestion des objets avec gestion du cycle de vie des informations"^].
