---
permalink: sg120-1200/replacing-fan-in-sg120-and-sg1200.html 
sidebar: sidebar 
keywords: storagegrid, sg120, sg1200, admin appliance, replacing, replace, fan, remove, removing, removal, install, installing 
summary: 'Les appareils SG120 ou SG1200 sont équipés de huit ventilateurs de refroidissement. Si l"un des ventilateurs tombe en panne, vous devez le remplacer dès que possible afin de garantir un refroidissement adéquat de l"appareil.' 
---
= Remplacer le ventilateur d'un SG120 ou SG1200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les appareils SG120 ou SG1200 sont équipés de sept ventilateurs de refroidissement. Si l'un des ventilateurs tombe en panne, vous devez le remplacer dès que possible afin de garantir un refroidissement adéquat de l'appareil.

.Description de la tâche
Pour éviter toute interruption de service, vérifiez que tous les autres nœuds de stockage sont connectés à la grille avant de commencer le remplacement du ventilateur ou remplacez le ventilateur dans une fenêtre de maintenance planifiée lorsque des périodes d'interruption de service sont acceptables. Voir les informations sur https://docs.netapp.com/us-en/storagegrid/monitor/monitoring-system-health.html#monitor-node-connection-states["contrôle de l'état de connexion du nœud"^].

Le nœud d'appliance ne sera pas accessible pendant le remplacement du ventilateur.

Les ventilateurs de refroidissement sont accessibles après avoir retiré le couvercle supérieur de l'appareil.


NOTE: Chacun des deux blocs d'alimentation contient également un ventilateur. Les ventilateurs du bloc d'alimentation ne sont pas inclus dans cette procédure.

.Avant de commencer
* Vous disposez du ventilateur de remplacement approprié.
* Vous avez link:verify-component-to-replace.html["déterminez l'emplacement du ventilateur à remplacer - effectué"].
* Vous avez link:locating-sg120-and-sg1200-in-data-center.html["l'appareil SG120 ou SG1200 situé physiquement"] où vous remplacez le ventilateur dans le centre de données.
+

NOTE: A link:power-sg120-and-sg1200-off-on.html#shut-down-the-sg120-or-sg1200-appliance["arrêt contrôlé de l'appareil"] est requis avant de retirer l'appareil du rack.

* Vous avez débranché tous les câbles et link:reinstalling-sg120-and-sg1200-cover.html["retirez le capot de l'appareil - effectué"].
* Vous avez confirmé que les autres ventilateurs sont installés et en cours d'exécution.


.Étapes
. Enroulez l'extrémité du bracelet antistatique autour de votre poignet et fixez l'extrémité du clip à une masse métallique afin d'éviter toute décharge statique.
. Localisez le ventilateur que vous devez remplacer.
+
Les sept ventilateurs sont situés aux emplacements suivants dans le châssis (moitié avant de l'appliance StorageGRID, capot supérieur retiré, illustrée) :

+
image::../media/drw_fan_position_ieops-2614.svg[Emplacements des ventilateurs dans le châssis de l'appliance StorageGRID]

+
|===
| Position du châssis | Ventilateur 


 a| 
1
 a| 
Fan_SYS0



 a| 
2
 a| 
Ventilateur_SYS1



 a| 
3
 a| 
Ventilateur_SYS2



 a| 
4
 a| 
FAN_SYS3



 a| 
5
 a| 
Ventilateur_SYS4



 a| 
6
 a| 
Ventilateur_SYS5



 a| 
7
 a| 
Ventilateur_SYS6

|===
. Soulevez le ventilateur défectueux hors du châssis à l'aide des languettes bleues.
+
image:../media/drw_s2025_fan_replace_ieops-2552.svg["Retirer un ventilateur du châssis"]

. Faites glisser le ventilateur de remplacement dans le logement ouvert du châssis.
+
Alignez le connecteur du ventilateur avec la prise du circuit imprimé.

. Enfoncer fermement le connecteur du ventilateur dans la carte de circuit imprimé.
. link:reinstalling-sg120-and-sg1200-cover.html["Replacez le couvercle supérieur sur l'appareil"], et appuyez sur le loquet pour fixer le couvercle en place.
. link:power-sg120-and-sg1200-off-on.html["Mettez l'appareil sous tension"] et surveillez les voyants LED de l'appareil et les codes de démarrage.
+
Utilisez l'interface BMC pour surveiller l'état de démarrage.

. Vérifiez que le nœud de l'appliance s'affiche dans Grid Manager et qu'aucune alerte n'apparaît.


Après avoir remplacé la pièce, retournez la pièce défectueuse à NetApp, comme indiqué dans les instructions RMA fournies avec le kit. Consultez la page  https://mysupport.netapp.com/site/info/rma["Retours et remplacements de pièces"^] pour plus d'informations.
