---
sidebar: sidebar 
permalink: storagegrid-enable.html 
keywords: storagegrid, how to enable, third-party solutions, tools, applications, examples 
summary: Découvrez comment tester et intégrer des applications dans votre environnement StorageGRID. 
---
= Solutions et ressources StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Aller à https://docs.netapp.com/us-en/storagegrid-enable/index.html["Solutions et ressources StorageGRID"^] pour apprendre à tester et activer des applications dans votre environnement StorageGRID .

* Les solutions et ressources StorageGRID * fournissent des exemples et des livres de recettes qui développent la documentation produit de ce site et décrivent certaines des prochaines étapes de l'évaluation et de l'intégration avec StorageGRID.

Voici quelques-unes des informations incluses :

* Liste des solutions tierces validées pour les versions StorageGRID passées et actuelles.
* Guides des fonctionnalités des produits. Par exemple, ces guides fournissent toutes les informations dont vous avez besoin pour créer des pools de stockage cloud.
* Guides d'utilisation et d'outils.
* Exemples d'API pour l'utilisation de fonctionnalités StorageGRID telles que le chiffrement S3 et le verrouillage d'objet S3.

