---
sidebar: sidebar 
permalink: whats-new-appliances.html 
keywords: storagegrid, appliance, whats new 
summary: Découvrez les nouveautés de ce site de documentation. 
---
= Nouveautés des appliances
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés des appliances StorageGRID.



== Informations sur les BMC

Des informations détaillées sur l'utilisation de l'interface BMC de l'appliance StorageGRID sont disponibles. Voir link:./commonhardware/use-bmc.html["Utilisation du contrôleur de gestion de la carte mère (BMC) de l'appliance StorageGRID"].



== Appareils SG5812 et SG5860

Les nouvelles appliances StorageGRID SG5812 et SG5860 sont des plateformes de stockage et de calcul intégrées qui fonctionnent comme des nœuds de stockage dans un grid StorageGRID. Consultez le link:./installconfig/hardware-description-sg5800.html["Appareils SG5800 : présentation"] pour en savoir plus.



== Appliance SG6160

La nouvelle appliance StorageGRID SG6160 inclut un contrôleur de calcul et un tiroir de contrôleur de stockage contenant deux contrôleurs de stockage et 60 disques, ainsi que deux disques SSD NVMe pour la mise en cache. Des tiroirs d'extension de 60 disques peuvent également être ajoutés au SG6160. Voir link:./installconfig/hardware-description-sg6100.html["Appliances SGF6100 : présentation"] pour en savoir plus.



== Appliances de services SG110 et SG1100

Les nouvelles appliances de services StorageGRID SG110 et SG1100 sont une mise à jour matérielle évolutive qui améliore les performances d'administration et d'équilibrage de la charge. Voir link:./installconfig/hardware-description-sg110-and-1100.html["Appliance de services SG110 et SG1100 : présentation"].
