---
permalink: sg6200/replacing-fan-in-sg6200.html 
sidebar: sidebar 
keywords: storagegrid, sgf6212, sg6200-cn, sg6260, storage appliance, Replacing, replace, fan, remove, removing, removal, install, installing 
summary: 'L"appareil SGF6212 et le contrôleur SG6200-CN sont équipés de sept ventilateurs de refroidissement. Si l"un des ventilateurs tombe en panne, vous devez le remplacer dès que possible afin de garantir un refroidissement adéquat de l"appareil.' 
---
= Remplacer le ventilateur d'un SGF6212 ou SG6200-CN (SG6260)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'appareil SGF6212 et le contrôleur SG6200-CN sont équipés de sept ventilateurs de refroidissement. Si l'un des ventilateurs tombe en panne, vous devez le remplacer dès que possible afin de garantir un refroidissement adéquat de l'appareil.

.Description de la tâche
Pour éviter toute interruption de service, vérifiez que tous les autres nœuds de stockage sont connectés à la grille avant de commencer le remplacement du ventilateur ou remplacez le ventilateur dans une fenêtre de maintenance planifiée lorsque des périodes d'interruption de service sont acceptables. Voir les informations sur https://docs.netapp.com/us-en/storagegrid/monitor/monitoring-system-health.html#monitor-node-connection-states["contrôle de l'état de connexion du nœud"^].


CAUTION: Si vous avez déjà utilisé une règle ILM qui ne crée qu'une copie d'un objet, vous devez remplacer le ventilateur lors d'une fenêtre de maintenance planifiée, car vous risquez de perdre temporairement l'accès à ces objets au cours de cette procédure. Voir les informations sur https://docs.netapp.com/us-en/storagegrid/ilm/why-you-should-not-use-single-copy-replication.html["pourquoi ne pas utiliser la réplication à copie unique"^].

Le nœud d'appliance ne sera pas accessible pendant le remplacement du ventilateur.


NOTE: Chacun des deux blocs d'alimentation contient également un ventilateur. Les ventilateurs du bloc d'alimentation ne sont pas inclus dans cette procédure.

.Avant de commencer
* Vous disposez du ventilateur de remplacement approprié.
* Vous avez link:verify-component-to-replace.html["déterminez l'emplacement du ventilateur à remplacer - effectué"].
* Vous avez link:locating-sg6200-in-data-center.html["localisé physiquement l'appareil SGF6212 ou le contrôleur SG6200-CN"] où vous remplacez le ventilateur dans le centre de données.
+

NOTE: A link:power-sg6200-off-on.html#shut-down-the-sgf6212-appliance-or-sg6200-cn-controller["arrêt contrôlé de l'appareil"] est requis avant de retirer l'appareil du rack.

* Vous avez débranché tous les câbles et link:reinstalling-sg6200-cover.html["retirez le capot de l'appareil - effectué"].
* Vous avez confirmé que les autres ventilateurs sont installés et en cours d'exécution.


.Étapes
. Enroulez l'extrémité du bracelet antistatique autour de votre poignet et fixez l'extrémité du clip à une masse métallique afin d'éviter toute décharge statique.
. Localisez le ventilateur que vous devez remplacer.
+
Les sept ventilateurs sont situés aux emplacements suivants dans le châssis (moitié avant de l'appliance StorageGRID, capot supérieur retiré, illustrée) :

+
image::../media/drw_fan_position_ieops-2614.svg[Emplacements des ventilateurs dans le châssis de l'appliance StorageGRID]

+
|===
| Position du châssis | Ventilateur 


 a| 
1
 a| 
Fan_SYS0



 a| 
2
 a| 
Ventilateur_SYS1



 a| 
3
 a| 
Ventilateur_SYS2



 a| 
4
 a| 
FAN_SYS3



 a| 
5
 a| 
Ventilateur_SYS4



 a| 
6
 a| 
Ventilateur_SYS5



 a| 
7
 a| 
Ventilateur_SYS6

|===
. Soulevez le ventilateur défectueux hors du châssis à l'aide des languettes bleues.
+
image:../media/drw_s2025_fan_replace_ieops-2552.svg["Retirer un ventilateur du châssis"]

. Faites glisser le ventilateur de remplacement dans le logement ouvert du châssis.
+
Alignez le connecteur du ventilateur avec la prise du circuit imprimé.

. Enfoncer fermement le connecteur du ventilateur dans la carte de circuit imprimé.
. link:reinstalling-sg6200-cover.html["Replacez le couvercle supérieur sur l'appareil"], puis appuyez sur le loquet pour fixer le couvercle en place.
. link:power-sg6200-off-on.html["Mettez l'appareil sous tension"] et surveiller les voyants LED de l'appareil et les codes de démarrage.
+
Utilisez l'interface BMC pour surveiller l'état de démarrage.

. Vérifiez que le nœud de l'appliance s'affiche dans Grid Manager et qu'aucune alerte n'apparaît.


Après avoir remplacé la pièce, retournez la pièce défectueuse à NetApp, comme indiqué dans les instructions RMA fournies avec le kit. Consultez la page  https://mysupport.netapp.com/site/info/rma["Retours et remplacements de pièces"^] pour plus d'informations.
