---
permalink: sg6200/replacing-sg6200-cn-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg6200, storage node, storage appliance, Replacing, replace, sg6200-cn, controller, remove, removing, removal, install, installing, installation 
summary: 'Il se peut que vous deviez remplacer le contrôleur SG6200-CN s"il ne fonctionne pas de manière optimale ou s"il est tombé en panne.' 
---
= Remplacer le contrôleur SG6200-CN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il se peut que vous deviez remplacer le contrôleur SG6200-CN s'il ne fonctionne pas de manière optimale ou s'il est tombé en panne.

.Description de la tâche
Le nœud de stockage de l'appliance sera inaccessible lors du remplacement du contrôleur SG6200-CN. Si le contrôleur SG6200-CN fonctionne correctement, vous pouvez effectuer un arrêt contrôlé au début de cette procédure.


NOTE: Si vous remplacez le contrôleur avant d'installer le logiciel StorageGRID, il se peut que vous ne puissiez pas accéder au programme d'installation de l'appliance StorageGRID immédiatement après avoir terminé cette procédure. Bien que vous puissiez accéder au programme d'installation de l'appliance StorageGRID à partir d'autres hôtes situés sur le même sous-réseau que l'appliance, vous ne pouvez pas y accéder à partir d'hôtes situés sur d'autres sous-réseaux. Cette condition doit se résoudre dans les 15 minutes (lorsque les entrées du cache ARP pour le contrôleur d'origine sont écoulées), ou vous pouvez effacer immédiatement la condition en éliminant manuellement les anciennes entrées du cache ARP à partir du routeur ou de la passerelle local.

.Avant de commencer
* Vous disposez d'un contrôleur de remplacement avec la même référence que le contrôleur que vous remplacez. Vérifier les étiquettes fixées à l'avant des contrôleurs pour s'assurer que les références correspondent.
* Vous avez des étiquettes pour identifier chaque câble connecté au contrôleur.
* Vous avez trouvé le contrôleur à remplacer dans le data Center.
+
link:locating-sg6200-in-data-center.html["Localiser le contrôleur dans le data Center"]



.Étapes
. Affichez les configurations actuelles de l'appareil et enregistrez-les.
+
.. Connectez-vous à l'appliance à remplacer :
+
... Saisissez la commande suivante : `ssh admin@_grid_node_IP_`
... Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
... Entrez la commande suivante pour passer à la racine : `su -`
... Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.



.. Entrez : `*run-host-command ipmitool lan print*` Pour afficher les configurations BMC actuelles de l'appliance.


. Si le contrôleur SG6200-CN fonctionne suffisamment pour permettre un arrêt contrôlé, link:power-sg6200-off-on.html["éteignez le contrôleur SG6200-CN"].
. Si l'une des interfaces réseau de cette appliance StorageGRID est configurée pour DHCP, vous devrez peut-être mettre à jour les attributions de bail DHCP permanentes sur les serveurs DHCP pour référencer les adresses MAC de l'appliance de remplacement. Cette mise à jour garantit que l'appliance se voit attribuer les adresses IP attendues.
. Retirez et remplacez le contrôleur SG6200-CN :
+
.. Etiquetez puis débranchez les câbles.
+

CAUTION: Pour éviter toute dégradation des performances, ne tordez pas, ne pliez pas, ne pincez pas ou ne montez pas sur les câbles.

.. Retirez le contrôleur défectueux de l'armoire ou du rack.
.. Installez le contrôleur de remplacement dans l'armoire ou le rack.
.. Remplacez les câbles.
.. Mettez le contrôleur sous tension et surveillez les LED du contrôleur.


. Si le chiffrement de disque matériel de l'appliance que vous avez remplacée est activé pour les disques SED, vous devez le faire https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-enabling-node-encryption.html#access-an-encrypted-drive["saisissez la phrase de passe de cryptage du lecteur"] pour accéder aux disques chiffrés lorsque l'appliance de remplacement démarre pour la première fois.
. Si l'appliance sur laquelle vous avez remplacé le contrôleur a utilisé un serveur de gestion des clés (KMS) pour chiffrer les données, il est possible que vous ayez besoin d'une configuration supplémentaire avant que le nœud puisse rejoindre la grille. Si le nœud ne rejoint pas automatiquement la grille, assurez-vous que ces paramètres de configuration ont été transférés vers le nouveau contrôleur et configurez manuellement les paramètres qui ne possèdent pas la configuration attendue :
+
** link:../installconfig/configuring-network-links.html["Configurer les liaisons réseau"]
** link:../installconfig/setting-ip-configuration.html["Configurez les adresses IP StorageGRID"]
** https://docs.netapp.com/us-en/storagegrid/admin/kms-overview-of-kms-and-appliance-configuration.html#set-up-the-appliance["Configurez le chiffrement des nœuds pour l'appliance"^]


. Connectez-vous à l'appliance avec le contrôleur remplacé :
+
.. Saisissez la commande suivante : `ssh admin@_grid_node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour passer à la racine : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.


. Restaurez la connectivité réseau du contrôleur BMC pour l'appliance. Deux options sont disponibles :
+
** Utilisez une adresse IP statique, un masque de réseau et une passerelle
** Utilisez DHCP pour obtenir une adresse IP, un masque de réseau et une passerelle
+
... Pour restaurer la configuration du contrôleur BMC afin d'utiliser une adresse IP statique, un masque de réseau et une passerelle, entrez les commandes suivantes :
+
`*run-host-command ipmitool lan set 1 ipaddr _Appliance_IP_*`

+
`*run-host-command ipmitool lan set 1 netmask _Netmask_IP_*`

+
`*run-host-command ipmitool lan set 1 defgw ipaddr _Default_gateway_*`

... Pour restaurer la configuration du contrôleur BMC afin d'utiliser DHCP pour obtenir une adresse IP, un masque de réseau et une passerelle, entrez la commande suivante :
+
`*run-host-command ipmitool lan set 1 ipsrc dhcp*`





. Après avoir restauré la connectivité réseau du contrôleur BMC, connectez-vous à l'interface du contrôleur BMC pour vérifier et restaurer toute configuration BMC personnalisée supplémentaire que vous avez éventuellement appliquée. Par exemple, vous devez confirmer les paramètres des destinations d'interruption SNMP et des notifications par e-mail. Voir link:../installconfig/configuring-bmc-interface.html["Configurer l'interface BMC"].
. Vérifiez que le nœud de l'appliance s'affiche dans Grid Manager et qu'aucune alerte n'apparaît.


Après avoir remplacé la pièce, retournez la pièce défectueuse à NetApp, comme indiqué dans les instructions RMA fournies avec le kit. Consultez la page  https://mysupport.netapp.com/site/info/rma["Retours et remplacements de pièces"^] pour plus d'informations.
