---
permalink: installconfig/configuring-bmc-interface.html 
sidebar: sidebar 
keywords: BMC, baseboard management controller, configure, setup, set up 
summary: 'L"interface utilisateur du contrôleur de gestion de la carte de base \(BMC\) sur le système SG6100, SG6000 ou services fournit des informations sur l"état du matériel et vous permet de configurer les paramètres SNMP et d"autres options pour les appliances.' 
---
= Interface BMC : présentation (SG100, SG1000, SG6000 et SG6100)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interface utilisateur du contrôleur BMC (Baseboard Management Controller) sur le système SG6100, SG6000 ou services fournit des informations sur l'état du matériel et vous permet de configurer les paramètres SNMP et d'autres options pour les appliances.

Utilisez les procédures suivantes de cette section pour configurer le contrôleur BMC lors de l'installation de l'appliance :

* link:../installconfig/changing-root-password-for-bmc-interface.html["Modifier le mot de passe admin ou root de l'interface BMC"]
* link:../installconfig/setting-ip-address-for-bmc-management-port.html["Définissez l'adresse IP du port de gestion BMC"]
* link:../installconfig/accessing-bmc-interface.html["Accéder à l'interface BMC"]
* link:../installconfig/configuring-snmp-settings-for-bmc.html["Configurer les paramètres SNMP"]
* link:../installconfig/setting-up-email-notifications-for-alerts.html["Configurez les notifications par e-mail pour les alertes BMC"]


[NOTE]
====
Si l'appliance a déjà été installée dans une grille et exécute le logiciel StorageGRID, procédez comme suit :

* link:../commonhardware/placing-appliance-into-maintenance-mode.html["Mettez l'appareil en mode de maintenance"] Pour accéder au programme d'installation de l'appliance StorageGRID.
* Voir link:../installconfig/setting-ip-address-for-bmc-management-port.html["Définissez l'adresse IP du port de gestion BMC"] Pour plus d'informations sur l'accès à l'interface BMC à l'aide du programme d'installation de l'appliance StorageGRID.


====