---
permalink: installconfig/configuring-hardware.html 
sidebar: sidebar 
keywords: storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking 
summary: 'Après avoir mis l"appareil sous tension, vous configurez les connexions réseau qui seront utilisées par StorageGRID. ' 
---
= Configuration du matériel : présentation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir mis l'appareil sous tension, vous configurez les connexions réseau qui seront utilisées par StorageGRID.



== Configurez les connexions réseau requises

Pour tous les dispositifs, vous devez effectuer plusieurs tâches pour configurer les connexions réseau requises, telles que :

* Accédez au programme d'installation de l'appliance
* Configurer les liaisons réseau
* Vérifiez les connexions réseau au niveau des ports




== Configuration supplémentaire éventuellement nécessaire

Selon le type d'appliance que vous configurez, une configuration matérielle supplémentaire peut être nécessaire.



=== SANtricity System Manager

Pour les systèmes SG6160, SG6000, SG5800 et SG5700, vous configurez SANtricity System Manager. Le logiciel SANtricity est utilisé pour contrôler le matériel de ces dispositifs.



=== Interface BMC

Les appliances suivantes ont une interface BMC qui doit être configurée :

* SG100
* SG110
* SG1000
* SG1100
* SG6000
* SG6100




== Configuration facultative

* Appliances de stockage
+
** Configurez le logiciel SANtricity System Manager (SG5700, SGS5800, SG6000 et SG6100) que vous utiliserez pour surveiller le matériel
** Changer de mode RAID
** link:../installconfig/accessing-bmc-interface.html["Accéder à l'interface BMC"] Pour le contrôleur SG6000-CN ou SG6100-CN


* Appliances de services
+
** link:../installconfig/accessing-bmc-interface.html["Accéder à l'interface BMC"] Pour les systèmes SG100, SG110, SG1000 et SG1100



