---
permalink: installconfig/obtaining-additional-equipment-and-tools.html 
sidebar: sidebar 
keywords: equipment to install appliance, tools for installation 
summary: 'Avant d"installer une appliance StorageGRID, vérifiez que vous disposez de tous les équipements et outils supplémentaires dont vous avez besoin.' 
---
= Obtenez des équipements et des outils supplémentaires pour les appliances StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'installer une appliance StorageGRID, vérifiez que vous disposez de tous les équipements et outils supplémentaires dont vous avez besoin.



== Tous les appareils

Vous avez besoin de l'équipement suivant pour installer et configurer tous les dispositifs.

Tournevis::
+
--
* N° Phillips 2 tournevis
* Tournevis plat moyen


--
Bracelet antistatique::
+
--
* https://docs.netapp.com/us-en/storagegrid/admin/web-browser-requirements.html["Navigateur Web pris en charge"^]
* Client SSH, tel que PuTTY
* Port 1 GbE (RJ-45)


--



NOTE: Certains ports ne prennent pas en charge les débits Ethernet 10/100.

Outils en option::
+
--
* Perceuse électrique avec embout Phillips
* Lampe de poche


--




== Équipements et outils spécifiques aux appareils

[role="tabbed-block"]
====
.SG100 et SG1000
--
Vous avez besoin de l'équipement supplémentaire suivant pour installer et configurer le matériel SG100 et SG1000.

Câbles optiques et émetteurs-récepteurs::
+
--
* Câbles, 1 à 4 de l'un ou l'autre :
+
** Twinax/cuivre
** Fibre optique


* Émetteurs-récepteurs/adaptateurs, 1 à 4 de chaque, en fonction de la vitesse de liaison (les vitesses mixtes ne sont pas prises en charge) :
+
** SG100 :
+
*** SFP+ 10 GbE
*** 25 GbE SFP28


** SG1000 :
+
*** Adaptateur QSFP-to-SFP (QSA) et SFP+ 10 GbE
*** Adaptateur QSFP-to-SFP (QSA) à 25 GbE et SFP28
*** QSFP+ 40 GbE
*** QSFP28 à 100 GbE






--
Câbles Ethernet:: RJ-45 (Cat5/Cat5e/Cat6/Cat6a)


--
.SG110 et SG1100
--
Vous avez besoin de l'équipement supplémentaire suivant pour installer et configurer le matériel SG110 et SG1100.

Câbles optiques et émetteurs-récepteurs::
+
--
* Câbles, 1 à 4 de l'un ou l'autre :
+
** Twinax/cuivre
** Fibre optique


* Émetteurs-récepteurs/adaptateurs, 1 à 4 de chaque, en fonction de la vitesse de liaison (les vitesses mixtes ne sont pas prises en charge) :
+
** SG110 :
+
*** SFP+ 10 GbE
*** 25 GbE SFP28


** SG1100 :
+
*** Adaptateur QSFP-to-SFP (QSA) et SFP+ 10 GbE
*** Adaptateur QSFP-to-SFP (QSA) à 25 GbE et SFP28
*** QSFP+ 40 GbE
*** QSFP28 à 100 GbE






--
Câbles Ethernet:: RJ-45 (Cat5/Cat5e/Cat6/Cat6a)


--
.SG120 et SG1200
--
Vous aurez besoin des équipements supplémentaires suivants pour installer et configurer le matériel SG120 et SG1200.

Câbles optiques et émetteurs-récepteurs::
+
--
* Câbles, 1 à 4 de l'un ou l'autre :
+
** Twinax/cuivre
** Fibre optique


* Émetteurs-récepteurs/adaptateurs, 1 à 4 de chaque, en fonction de la vitesse de liaison (les vitesses mixtes ne sont pas prises en charge) :
+
** SG120 :
+
*** SFP+ 10 GbE
*** 25 GbE SFP28


** SG1200 :
+
*** Adaptateur QSFP-to-SFP (QSA) et SFP+ 10 GbE
*** Adaptateur QSFP-to-SFP (QSA) à 25 GbE et SFP28
*** QSFP+ 40 GbE
*** QSFP28 à 100 GbE
*** 200-GbE QSFP56 (carte réseau 200GbE uniquement)






--
Câbles Ethernet:: RJ-45 (Cat5/Cat5e/Cat6/Cat6a)


--
.SG5700
--
Vous avez besoin des équipements supplémentaires suivants pour installer et configurer le matériel SG5700.

Câbles optiques et émetteurs-récepteurs SFP::
+
--
* Câbles optiques pour les ports 10/25 GbE que vous souhaitez utiliser
* Facultatif : les émetteurs-récepteurs SFP28 si vous souhaitez utiliser la vitesse de liaison 25 GbE


--
Câbles Ethernet:: Levage mécanisé pour SG5760


--
.SG5800
--
Vous avez besoin de l'équipement supplémentaire suivant pour installer et configurer le matériel SG5800.

Câbles et émetteurs-récepteurs SFP::
+
--
* Câbles pour les ports 10/25-GbE que vous prévoyez d'utiliser
* Facultatif : émetteurs-récepteurs SFP28 si vous souhaitez utiliser une vitesse de liaison 25 GbE avec des câbles optiques
* En option : émetteurs-récepteurs SFP+ si vous souhaitez utiliser une vitesse de liaison 10 GbE et des câbles optiques


--
Câbles Ethernet:: Levage mécanisé pour SG5860


--
.SG6000
--
Vous avez besoin de l'équipement supplémentaire suivant pour installer et configurer le matériel SG6000.

Câbles optiques et émetteurs-récepteurs SFP::
+
--
* Câbles, 1 à 4 de l'un ou l'autre :
+
** Twinax/cuivre
** Fibre optique


* Émetteurs-récepteurs/adaptateurs, 1 à 4 de chaque, en fonction de la vitesse de liaison (les vitesses mixtes ne sont pas prises en charge) :
+
** SFP+ 10 GbE
** 25 GbE SFP28




--
Câbles Ethernet:: RJ-45 (Cat5/Cat5e/Cat6)
Outils en option:: Levage mécanisé pour les tiroirs de 60 disques


--
.SG6100
--
Vous avez besoin de l'équipement supplémentaire suivant pour installer et configurer le matériel SG6100.

Câbles et émetteurs-récepteurs::
+
--
* Câbles, 1 à 4 de l'un ou l'autre :
+
** Twinax/cuivre
** Fibre optique


* Émetteurs-récepteurs/adaptateurs, 1 à 8 de chaque, en fonction de la vitesse de liaison (les vitesses mixtes ne sont pas prises en charge) :
+
** SFP+ 10 GbE
** 25 GbE SFP28
** QSFP28 à 100 GbE




--
Câbles Ethernet:: RJ-45 (Cat5/Cat5e/Cat6/Cat6a)
Outils en option:: Levage mécanisé pour les tiroirs de 60 disques


--
.SG6200
--
Vous avez besoin de l'équipement supplémentaire suivant pour installer et configurer le matériel SG6100.

Câbles et émetteurs-récepteurs::
+
--
* Câbles, 1 à 4 de l'un ou l'autre :
+
** Twinax/cuivre
** Fibre optique


* Émetteurs-récepteurs/adaptateurs, 1 à 8 de chaque, en fonction de la vitesse de liaison (les vitesses mixtes ne sont pas prises en charge) :
+
** SFP+ 10 GbE
** 25 GbE SFP28
** QSFP+ 40 GbE
** QSFP28 à 100 GbE
** QSFP56 200-GbE (carte réseau 200-GbE uniquement)




--
Câbles Ethernet:: RJ-45 (Cat5/Cat5e/Cat6/Cat6a)
Outils en option:: Levage mécanisé pour les tiroirs de 60 disques


--
====