---
permalink: sg6100/upgrading-santricity-os-on-storage-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg5800, storage node, storage appliance, controller, storage controller, upgrade, upgrading, SANtricity OS, SANtricity 
summary: 'Pour optimiser le fonctionnement du contrôleur de stockage, vous devez effectuer une mise à niveau vers la dernière version de maintenance du système d"exploitation SANtricity compatible avec votre appliance StorageGRID.' 
---
= Mise à niveau du système d'exploitation SANtricity sur le contrôleur de stockage SG6160
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour optimiser le fonctionnement du contrôleur de stockage, vous devez effectuer une mise à niveau vers la dernière version de maintenance du système d'exploitation SANtricity compatible avec votre appliance StorageGRID.

Déterminez la dernière version de SANtricity OS compatible avec votre appliance StorageGRID en la consultant et en https://mysupport.netapp.com/site/products/all/details/storagegrid-appliance/downloads-tab["Téléchargement NetApp : appliance StorageGRID"^] la téléchargeant si nécessaire.

Téléchargez le nouveau fichier du logiciel SANtricity OS sur https://mysupport.netapp.com/site/products/all/details/storagegrid-appliance/downloads-tab["Téléchargement NetApp : appliance StorageGRID"^].

Utilisez l'une des procédures suivantes basées sur la version de SANtricity OS actuellement installée :

* Vous pouvez utiliser le Gestionnaire de grille pour effectuer la mise à niveau.
+
link:upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg6160.html["Mettez à niveau le système d'exploitation SANtricity sur les contrôleurs de stockage à l'aide de Grid Manager"]

* Vous pouvez utiliser le mode maintenance pour effectuer la mise à niveau.
+
link:upgrading-santricity-os-on-e4000-controller-using-maintenance-mode.html["Mettez à niveau SANtricity OS sur le contrôleur E4000 en utilisant le mode de maintenance"]

+

NOTE: Pour les contrôleurs de stockage utilisant actuellement un système d'exploitation SANtricity plus récent que 08.42.20.00 (11.42), il est recommandé de link:upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg6160.html["Utilisez Grid Manager pour appliquer une mise à niveau"]. Toutefois, vous pouvez utiliser la procédure du mode maintenance si vous le préférez ou si vous y avez reçu des instructions du support technique.


