---
permalink: sg5800/replace-controller-5800sg.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Remplacer le contrôleur StorageGRID SG5800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devrez peut-être remplacer le contrôleur SG5800 s'il ne fonctionne pas de manière optimale ou s'il est défectueux.

.Avant de commencer
* Vous disposez d'un contrôleur de remplacement avec la même référence que le contrôleur que vous remplacez.
* Vous avez des étiquettes pour identifier chaque câble connecté au contrôleur.


.Description de la tâche
Vous ne pourrez pas accéder au nœud de stockage de l'appliance lorsque vous remplacerez le contrôleur.  Si le contrôleur SG5800 fonctionne suffisamment, vous pouvez effectuer un arrêt contrôlé au début de cette procédure.


NOTE: Si vous remplacez le contrôleur avant d'installer le logiciel StorageGRID, il se peut que vous ne puissiez pas accéder au programme d'installation de l'appliance StorageGRID immédiatement après avoir terminé cette procédure. Bien que vous puissiez accéder au programme d'installation de l'appliance StorageGRID à partir d'autres hôtes situés sur le même sous-réseau que l'appliance, vous ne pouvez pas y accéder à partir d'hôtes situés sur d'autres sous-réseaux. Cette condition doit se résoudre dans les 15 minutes (lorsque les entrées du cache ARP pour le contrôleur d'origine sont écoulées), ou vous pouvez effacer immédiatement la condition en éliminant manuellement les anciennes entrées du cache ARP à partir du routeur ou de la passerelle local.

.Étapes
. Arrêtez le contrôleur SG5800.
+
.. Connectez-vous au nœud grid :
+
... Saisissez la commande suivante : `ssh admin@grid_node_IP`
... Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
... Entrez la commande suivante pour passer à la racine : `su -`
... Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.





. Arrêtez le contrôleur SG5800 :
+
*`shutdown -h now`*

. Si les réseaux StorageGRID connectés au contrôleur utilisent des serveurs DHCP :
+
.. Notez les adresses MAC des ports du contrôleur de remplacement (situées sur les étiquettes du contrôleur).
.. Demandez à votre administrateur réseau de mettre à jour les paramètres d'adresse IP du contrôleur d'origine afin qu'ils reflètent les adresses MAC du contrôleur de remplacement.
+

NOTE: Vous devez vous assurer que les adresses IP du contrôleur d'origine ont été mises à jour avant d'insérer le contrôleur de remplacement dans l'appareil.  Dans le cas contraire, le contrôleur obtiendra de nouvelles adresses IP DHCP lors de son démarrage et risque de ne pas pouvoir se reconnecter à StorageGRID.  Cette étape s’applique à tous les réseaux StorageGRID connectés au contrôleur.



. Retirer le contrôleur de l'appliance :
+
.. Placez un bracelet antistatique ou prenez d'autres précautions antistatiques.
.. Etiqueter les câbles puis débrancher les câbles et les SFP.
+

NOTE: Pour éviter toute dégradation des performances, ne tordez pas, ne pliez pas, ne pincez pas et ne montez pas sur les câbles.
Libérez le contrôleur de l'appareil en appuyant sur le loquet de la poignée de came jusqu'à ce qu'il se relâche, puis ouvrez la poignée de came vers la droite.

.. A l'aide de deux mains et de la poignée de came, faites glisser le contrôleur hors de l'appareil.
+

NOTE: Toujours utiliser deux mains pour soutenir le poids du contrôleur.



. Installez le contrôleur de remplacement sur l'appliance.
+
.. Retournez le contrôleur pour que le capot amovible soit orienté vers le bas.
.. Avec la poignée de came en position ouverte, faites glisser le contrôleur complètement dans l'appareil.
.. Déplacez la poignée de came vers la gauche pour verrouiller le contrôleur en place.
.. Remplacez les câbles.


. Une fois le contrôleur redémarré et l'appareil rejoint le réseau, vérifiez que le nœud de stockage de l'appareil apparaît dans le gestionnaire de grille et qu'aucune alarme n'apparaît.


Après le remplacement de la pièce, renvoyez la pièce défectueuse à NetApp, en suivant les instructions RMA (retour de matériel) livrées avec le kit. Voir la https://mysupport.netapp.com/site/info/rma["Retour de pièce et amp ; remplacements"] pour plus d'informations.
